- .eslintrc.js
- index.js
- package.json
- src/App.js
- src/components/HamburgerButton.js
- src/components/TitleButton.js
- src/components/TitleLogo.js
- src/components/WebView.js
- src/constants.js
- src/screens/Web.js
- src/services/apollo.js
- src/services/authentication.js
- src/services/codePush.js
- src/services/deepLinking.js
- src/services/pushNotifications.js
- src/utils/url.js
- src/utils/webHistory.js
- yarn.lock
> Add eslint setup

- src/App.js
- src/apollo/index.js
- src/apollo/mutations.js
- src/apollo/queries.js
- src/components/HamburgerButton.js
- src/components/Menu.js
- src/components/TitleButton.js
- src/components/WebView.js
- src/screens/Web.js
- src/services/apollo.js
- src/services/pushNotifications.js
> Implement native menu

- ios/orbitingapp.xcodeproj/project.pbxproj
> Raise min version iOS to 9.3

- ios/orbitingapp.xcodeproj/project.pbxproj
- package.json
- src/components/WebView.js
- src/utils/translations.json
- src/utils/withT.js
- yarn.lock
@tpreusse someone should translate the texts to german 😄 
Uses own `react-native-wkwebview-reborn` fork, that fixes reload bug
Fixes #20
> Network error view

- src/apollo/index.js
- src/apollo/mutations.js
- src/components/TitleLogo.js
- src/components/WebView.js
- src/screens/Web.js
Save URL in global state. This enables to:
- Change navigation everywhere in the app
- Remember user's location for when starting the app again
> Save url in global state

- src/components/WebView.js
- src/screens/Web.js
- src/utils/webview.js
> Pull refresh

- ios/orbitingapp.xcodeproj/project.pbxproj
> Setup for iPad

- src/components/HamburgerButton.js
- src/components/Header.js
- src/components/TitleButton.js
> Increase clickable area for header buttons

- src/screens/Web.js
> Fix links not opening in app

- src/components/Header.js
- src/components/WebView.js
- src/screens/Web.js
- src/utils/webview.js
> Fix logo button

- src/utils/webview.js
> Improve pull to refresh logic

- docs/messages.md
> Add messages API documentation

- src/screens/Web.js
> Reload webview when coming from background

- android/app/src/main/java/app/republik/CustomWebView/CustomWebViewManager.java
- android/app/src/main/java/app/republik/CustomWebView/CustomWebViewModule.java
- android/app/src/main/java/app/republik/CustomWebView/CustomWebViewPackage.java
- android/app/src/main/java/app/republik/MainApplication.java
- ios/orbitingapp/AppDelegate.m
- src/components/AndroidWebView.js
- src/components/WebView.js
- src/screens/Web.js
- src/services/pushNotifications.ios.js
**Screenshot**
**Todo:**
Fixes #62
> Android upload (WIP)

- src/components/WebView.js
_Ex iOS:_
`Mozilla/5.0 (iPhone; CPU iPhone OS 11_4 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15F79 RepublikApp`
Ref #40 #99
> Send default user agent in addition of the RepublikApp

- src/components/AudioPlayer.js
> Switch playback on audio player

- src/screens/Web.js
> Fix pull to refresh

- src/apollo/queries.js
- src/components/WebView.js
- src/screens/Web.js
> Reload page at navigation when app was inactive for more than 1 hr

- src/components/Header.js
> Hide header search icon when user not signed in

- src/components/AudioPlayer.js
This also makes the "clickable" audio progress bar area a bit bigger, enhancing the UX
Fixes #128
> Don't initialize audio player until user wants to hear something

- .gitignore
- README.md
- docs/fonts.md
- ios/orbitingapp.xcodeproj/project.pbxproj
- ios/orbitingapp/Info.plist
- package.json
- src/components/AudioPlayer.js
- src/components/Header.js
- src/components/Subheader.js
- src/components/WebView.js
> Link and use fonts in project

- docs/messages.md
- src/screens/Web.js
> Post subheader state messages to frontend

- src/screens/Web.js
> Post subheader message only when changes

- src/App.js
- src/screens/Web.js
> Hide status bar when gallery open

- src/components/Subheader.js
- src/screens/Web.js
> Fix issue with subheader and gallery

- docs/messages.md
- src/App.js
- src/components/Header.js
- src/components/NavBar.js
- src/components/SafeAreaView.js
- src/screens/Login.js
- src/screens/Web.js
- src/utils/webview.js
- rename `Subheader` to `NavBar` (for consistency with frontend)
- make js injected message listener safer
- correct header and navbar heights
- `SafeAreaView` and landscape fixes
> Refactor R1

- src/components/WebView.js
- src/screens/Login.js
- src/screens/Web.js
Move to `onShouldLoad` concept and implement `onShouldStartLoadWithRequest` for iOS (reduced duplicate requests)
> Should Load

- src/services/pushNotificationsProvider.android.js
see: https://github.com/orbiting/backends/pull/304
> fix(notifications): skip rollDeviceToken on init

- android/app/build.gradle
- android/app/src/main/AndroidManifest.xml
- android/build.gradle
- android/fastlane/Fastfile
- ios/Podfile.lock
- ios/republikapp-tvOS/Info.plist
- ios/republikapp-tvOSTests/Info.plist
- ios/republikapp.xcodeproj/project.pbxproj
- ios/republikapp/Info.plist
- ios/republikappTests/Info.plist
- package.json
- src/components/AudioPlayer/Controls.js
- src/components/AudioPlayer/ExpandedControls.js
- src/components/AudioPlayer/ProgressBar.js
- src/components/AudioPlayer/index.js
- src/constants.js
- src/screens/Web.js
- yarn.lock
> playbackRate selection and expandable player

- android/app/build.gradle
- ios/republikapp-tvOS/Info.plist
- ios/republikapp-tvOSTests/Info.plist
- ios/republikapp.xcodeproj/project.pbxproj
- ios/republikapp/Info.plist
- ios/republikappTests/Info.plist
- package.json
- patches/react-native-status-bar-height+2.6.0.patch
> iOS v2.2.1: add patch for react-native-status-bar to work with dynamic-island

- android/app/build.gradle
- package.json
- src/components/AudioPlayer/HeadlessAudioPlayer.ts
- src/components/AudioPlayer/SetupAudioPlayerService.ts
- src/services/PlaybackService.js
- yarn.lock
https://rntp.dev/docs/v4-migration
@trm217 Upgrade necessary to fix a bug with compileSdkVersion 34.
> migrate trackplayer from 3.2 to 4.x
